### ISSUE TITLE
Make GraphProcesses composable

### ISSUE THREAD

**Issue by eparejatobes** [bio4j/bio4j-data-import#4]
The signature is `(Input,Graph) => (Graph,Output)`.

**Comment by eparejatobes** [comment]
The point is 
1. being able to split import processes into manageable components (import proteins, annotations, etc)
2. compose then in the right order (in terms of data that should be already there before) to build complete import processes

**Comment by laughedelic** [comment]
Are you going to do it? Or can I take it?

**Comment by eparejatobes** [comment]
As you please. It is neither essential nor high priority right now.

**Comment by laughedelic** [comment]
OK, then I'll try it later 👍

**Comment by eparejatobes** [comment]
Much outdated, closing.
